export const mockedData = [
  {
    "first-name": "Will",
    "last-name": "Smith",
    "date-of-birth": "01/01/1991",
    street: "10 rue du Cerisier",
    "start-date": "20/09/2022",
    state: "AL",
    city: "Montgomery",
    "zip-code": " 36043",
    department: "Marketing",
    key: "1",
  },
  {
    "first-name": "Brad",
    "last-name": "Pitt",
    "date-of-birth": "02/02/1992",
    street: "59 rue du pot-de-fleur",
    "start-date": "20/09/2022",
    state: "AL",
    city: "Montgomery",
    "zip-code": "36043",
    department: "Engineering",
    key: "2",
  },
  {
    "first-name": "Joseph",
    "last-name": "Gordon-Lewitt",
    "date-of-birth": "03/03/1993",
    street: "239 allée des vents",
    "start-date": "20/09/2022",
    state: "AL",
    city: "Montgomery",
    "zip-code": "36043",
    department: "Human",
    key: "3",
  },
];
