const firstName = [
  "Griselda",
  "Gavyn",
  "Camila",
  "Dante",
  "Joaquin",
  "Emerson",
  "Camren",
  "Dahlia",
  "Davion",
  "Candice",
  "Mariah",
  "Arron",
  "Denis",
  "Nicolas",
  "Laura",
  "Elyse",
  "Tasia",
  "Odalys",
  "Berenice",
  "Dequan",
  "Sarahi",
  "Orion",
  "Molly",
  "Aubrie",
  "Kaytlyn",
  "Cali",
  "Jacob",
  "Emmalee",
  "Killian",
  "Gilberto",
];
const lastName = [
  "Goss",
  "Putman",
  "Schweitzer",
  "Gleason",
  "Stubblefield",
  "Reeves",
  "Card",
  "Garrison",
  "Mancini",
  "Fuchs",
  "Bock",
  "Holton",
  "Hong",
  "Painter",
  "Eckert",
  "Buckner",
  "Acevedo",
  "Denton",
  "Cagle",
  "Steen",
  "Noriega",
  "Kimball",
  "Kuykendall",
  "Tyree",
  "Jean",
  "Worden",
  "Aponte",
  "Deal",
  "McGee",
  "Chao",
  "Tompkins",
  "Bowden",
  "Vetter",
  "Brock",
  "Peter",
  "Irby",
  "Dahl",
  "Halstead",
  "Estrada",
  "March",
  "Fowler",
  "Romero",
  "McNeal",
  "Ellison",
  "Perryman",
  "Finch",
  "Palma",
  "Mondragon",
  "Christy",
  "Hagen",
];
const streetName = [
"Judge Lane",
"Low Passage",
"Lotus Avenue",
"Lilypad Boulevard",
"Poplar Passage",
"Lavender Row",
"Corporation Row",
"Ironwood Lane",
"Queen Route",
"Vine Route",
"Garden Passage",
"Chestnut Avenue",
"Cannon Boulevard",
"Coastline Boulevard",
"Gem Row",
"Sugarplum Way",
"Park Row",
"Hind Lane",
"Medieval Lane",
"Rose Boulevard",
"Hazelnut Route",
"Lower Way",
"Main Lane",
"Oceanview Avenue",
"Ranger Street",
"Parkside Route",
"Prince Passage",
"Lumber Lane",
"Beaver Way",
"Shade Route",
"Fair Passage",
"Ivy Avenue",
"Beech Row",
"Judge Avenue",
"Wellness Way",
"Haven Lane",
"Pearl Row",
"Prince Route",
"Meadow Avenue",
"Beach Avenue",
];
const department = ["Sales", "Marketing", "Engineering", "Human", "Resources", "Legal"];
const states = [
  "Alabama",
  "Alaska",
  "American Samoa",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District Of Columbia",
  "Federated States Of Micronesia",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Marshall Islands",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Northern Mariana Islands",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Palau",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virgin Islands",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
const city = [
  "Aberdeen",
  "Abilene",
  "Akron",
  "Albany",
  "Albuquerque",
  "Alexandria",
  "Allentown",
  "Amarillo",
  "Anaheim",
  "Anchorage",
  "Ann Arbor",
  "Antioch",
  "Apple Valley",
  "Appleton",
  "Arlington",
  "Arvada",
  "Asheville",
  "Athens",
  "Atlanta",
  "Atlantic City",
  "Augusta",
  "Aurora",
  "Austin",
  "Bakersfield",
  "Baltimore",
  "Barnstable",
  "Baton Rouge",
  "Beaumont",
  "Bel Air",
  "Bellevue",
  "Berkeley",
  "Bethlehem",
  "Billings",
  "Birmingham",
  "Bloomington",
  "Boise",
  "Boise City",
  "Bonita Springs",
  "Boston",
  "Boulder",
  "Bradenton",
  "Bremerton",
  "Bridgeport",
  "Brighton",
  "Brownsville",
  "Bryan",
  "Buffalo",
  "Burbank",
  "Burlington",
  "Cambridge",
  "Canton",
  "Cape Coral",
  "Carrollton",
  "Cary",
  "Cathedral City",
  "Cedar Rapids",
  "Champaign",
  "Chandler",
  "Charleston",
  "Charlotte",
  "Chattanooga",
  "Chesapeake",
  "Chicago",
  "Chula Vista",
  "Cincinnati",
  "Clarke County",
  "Clarksville",
  "Clearwater",
  "Cleveland",
  "College Station",
  "Colorado Springs",
  "Columbia",
  "Columbus",
  "Concord",
  "Coral Springs",
  "Corona",
  "Corpus Christi",
  "Costa Mesa",
  "Dallas",
  "Daly City",
  "Danbury",
  "Davenport",
  "Davidson County",
  "Dayton",
  "Daytona Beach",
  "Deltona",
  "Denton",
  "Denver",
  "Des Moines",
  "Santa Cruz",
  "Santa Maria",
  "Santa Rosa",
  "Sarasota",
  "Savannah",
  "Scottsdale",
  "Scranton",
  "Seaside",
  "Seattle",
  "Sebastian",
  "Shreveport",
  "Simi Valley",
  "Sioux City",
  "Sioux Falls",
  "South Bend",
  "South Lyon",
  "Spartanburg",
  "Spokane",
  "Springdale",
  "Springfield",
  "St. Louis",
  "St. Paul",
  "St. Petersburg",
  "Stamford",
  "Sterling Heights",
  "Stockton",
  "Sunnyvale",
  "Syracuse",
  "Tacoma",
  "Tallahassee",
  "Tampa",
  "Temecula",
  "Tempe",
  "Thornton",
  "Thousand Oaks",
  "Toledo",
  "Topeka",
  "Torrance",
  "Trenton",
  "Tucson",
  "Tulsa",
  "Tuscaloosa",
  "Tyler",
  "Utica",
  "Vallejo",
  "Vancouver",
  "Vero Beach",
  "Victorville",
  "Virginia Beach",
  "Visalia",
  "Waco",
  "Warren",
  "Washington",
  "Waterbury",
  "Waterloo",
  "West Covina",
  "West Valley City",
  "Westminster",
  "Wichita",
  "Wilmington",
  "Winston",
  "Winter Haven",
  "Worcester",
  "Yakima",
  "Yonkers",
  "York",
  "Youngstown",
];

/**
 * Allows you to create a random employee to fill the table faster.
 * @returns an object that will be pushed into the "list" and "filteredList" array
 */
export const randomEmployee = () => {
  return {
    "first-name": firstName[Math.floor(Math.random() * (firstName.length - 0) + 0)],
    "last-name": lastName[Math.floor(Math.random() * (lastName.length - 0) + 0)],
    "date-of-birth": new Date(new Date() - Math.random() * 1e12).toLocaleDateString("En"),
    street: streetName[Math.floor(Math.random() * (streetName.length - 0) + 0)]+', '+(Math.floor(Math.random()* 9500-100) + 100),
    city: city[Math.floor(Math.random() * (city.length - 0) + 0)],
    state: states[Math.floor(Math.random() * (states.length - 0) + 0)],
    "zip-code": Math.floor(Math.random() * 9999 - 1000) + 1000,
    "start-date": new Date(new Date() - Math.random() * 1e12).toLocaleDateString("En"),
    department: department[Math.floor(Math.random() * (department.length - 0) + 0)],
    key: new Date().getTime(),
  };
};
